#!/usr/bin/env node

/**********************************
 * Provides a simple tool to open a tunnel to BrowserStack when running browser-srv manually and wanting to do manual testing
 *
 * Usage:
 * manual-tunnel [ports,split,by,commas]
 *
 **********************************/

var fs = require('fs'),
    childProcess = require('child_process'),
    path = require('path'),
    config;

try {
  config = JSON.parse(fs.readFileSync(path.normalize(__dirname + '/browser-stack.json')));
} catch (e) {
  console.error('Could not load browser-stack.json configuration.  Please ensure this exists and follows the format in browser-stack.json.example');
  console.error('Error: ' + e.message);
  process.exit(1);
}

var tunnelPorts;

if (!process.argv[2]) {
  console.warn('You did not specify any ports, we will default to ports commonly used with a simple farm: 843,8092,8080,8081');
  tunnelPorts = ['843','8092','8080','8081'];
} else {
  tunnelPorts = process.argv[2].split(',');
}

var tunnelHosts = tunnelPorts.map(function (e) { return 'localhost,' + e + ',0'; }),
    tunnelArgs = ['-jar', path.normalize(__dirname + '/bin/BrowserStackTunnel.jar'), config['credentials']['manual_testing_tunnel_key'],tunnelHosts.join(',')];

tunnelProcess = childProcess.spawn('java', tunnelArgs);
tunnelProcess.stdout.pipe(process.stdout);
tunnelProcess.stderr.pipe(process.stderr);
tunnelProcess.on('exit', function(code, signal) {
  console.error('Tunnel has closed: ' + code + ', ' + signal);
  process.exit();
});

console.log('Tunnel opened to BrowserStack for ports ' + tunnelPorts.join(', '));

if ((tunnelPorts.indexOf('8092') == -1) || (tunnelPorts.indexOf('843') == -1)) console.warn('\n! The test server runs on port 8092 and serves Flash policies on 843, did you mean to leave those ports out?\n');

setInterval(function() {}, 1000);