// Message, presence and annotation data-model type declarations for the Ably Pub/Sub SDK packages.
import type { ChannelOptions } from './channels';

/**
 * Contains an individual message that is sent to, or received from, Ably.
 */
export interface Message {
  /**
   * The client ID of the publisher of this message.
   */
  clientId?: string;
  /**
   * The connection ID of the publisher of this message.
   */
  connectionId?: string;
  /**
   * The message payload, if provided.
   */
  data?: any;
  /**
   * This is typically empty, as all messages received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute contains the remaining transformations not applied to the `data` payload.
   */
  encoding?: string;
  /**
   * A JSON object of arbitrary key-value pairs that may contain metadata, and/or ancillary payloads. Valid payloads include `push`, `delta`, `ref` and `headers`.
   */
  extras?: any;
  /**
   * An ID associated with the message. Clients may set this field explicitly when publishing a message to enable
   * idempotent publishing. If not set, this will be generated by the server.
   *
   * For the canonical identifier of the message on the server, see `serial`.
   */
  id?: string;
  /**
   * The event name.
   */
  name?: string;
  /**
   * Timestamp of when the message was received by Ably, as milliseconds since the Unix epoch.
   * (This is the timestamp of the current version of the message)
   */
  timestamp?: number;
  /**
   * The action type of the message, one of the {@link MessageAction} enum values.
   */
  action?: MessageAction;
  /**
   * This message's unique serial (an identifier that will be the same in all future
   * updates of this message).
   */
  serial?: string;
  /**
   * The latest version of the message, containing version-specific metadata.
   */
  version?: MessageVersion;
  /**
   * Allows an HTTP client to publish a message on behalf of a Realtime client. If you set this to the {@link Connection.key | private connection key} of a Realtime connection when publishing a message using an `HttpClient`, the message will be published on behalf of that Realtime client. This property is only populated by a client performing a publish, and will never be populated on an inbound message.
   */
  connectionKey?: string;
  /**
   * Annotations associated with this message.
   */
  annotations?: MessageAnnotations;
}

/**
 * An annotation to a message, received from Ably
 */
export interface Annotation {
  /**
   * Unique ID assigned by Ably to this annotation.
   */
  id: string;
  /**
   * The client ID of the publisher of this annotation (if any).
   */
  clientId?: string;
  /**
   * The name of this annotation. This is the field that most annotation aggregations will
   * operate on. For example, using "distinct.v1" aggregation (specified in the type), the
   * message summary will show a list of clients who have published an annotation with
   * each distinct annotation.name.
   */
  name?: string;
  /**
   * An optional count, only relevant to certain aggregation types, see aggregation types
   * documentation for more info.
   */
  count?: number;
  /**
   * An arbitrary publisher-provided payload, if provided. Not aggregated.
   */
  data?: any;
  /**
   * The encoding of the payload; typically empty as the data is decoded client-side back
   * into the original data type.
   */
  encoding?: string;
  /**
   * Timestamp of when the annotation was received by Ably, as milliseconds since the Unix epoch.
   */
  timestamp: number;
  /**
   * The action, whether this is an annotation being added or removed, one of the {@link AnnotationAction} enum values.
   */
  action: AnnotationAction;
  /**
   * This message's unique serial (lexicographically totally ordered).
   */
  serial: string;
  /**
   * The serial of the message (of type message.create) that this annotation is annotating.
   */
  messageSerial: string;
  /**
   * The type of annotation it is, typically some name together with an aggregation
   * method; for example: "emoji:distinct.v1". Handled opaquely by the SDK and validated serverside.
   */
  type: string;
  /**
   * A JSON object for metadata and/or ancillary payloads.
   */
  extras: any;
}

/**
 * A variant of the Annotation type customized for those fields which need to be populated
 * by the user when publishing an annotation.
 */
export type OutboundAnnotation = Partial<Annotation> & {
  /**
   * The type of annotation it is, typically some name together with an aggregation
   * method; for example: "emoji:distinct.v1". Handled opaquely by the SDK and validated serverside.
   */
  type: string;
};

/**
 * Contains the details regarding the current version of the message - including when it was updated and by whom.
 */
export interface MessageVersion {
  /**
   * A unique identifier for the version of the message, lexicographically-comparable with other versions (that
   * share the same `Message.serial`). Will differ from the `Message.serial` only if the message has been
   * updated or deleted.
   */
  serial?: string;
  /**
   * The timestamp of the message version.
   *
   * If the `Message.action` is `message.create`, this will equal the `Message.timestamp`.
   */
  timestamp?: number;
  /**
   * The client ID of the client that updated the message to this version.
   */
  clientId?: string;
  /**
   * The description provided by the client that updated the message to this version.
   */
  description?: string;
  /**
   * A JSON object of string key-value pairs that may contain metadata associated with the operation to update
   * the message to this version.
   */
  metadata?: Record<string, string>;
}

/**
 * Contains information about annotations associated with a particular message.
 */
export interface MessageAnnotations {
  /**
   * A summary of all the annotations that have been made to the message. Will always be
   * populated for a message.summary, and may be populated for any other type (in
   * particular a message retrieved from REST history will have its latest summary
   * included).
   * The keys of the map are the annotation types. The exact structure of the value of
   * each key depends on the aggregation part of the annotation type, e.g. for a type of
   * reaction:distinct.v1, the value will be a DistinctValues object. New aggregation
   * methods might be added serverside, hence the 'unknown' part of the sum type.
   */
  summary: Record<string, SummaryEntry>;
}

/**
 * Contains metadata about a message update or delete operation.
 */
export interface MessageOperation {
  /**
   * Optional identifier of the client performing the operation.
   */
  clientId?: string;
  /**
   * Optional human-readable description of the operation.
   */
  description?: string;
  /**
   * Optional dictionary of key-value pairs containing additional metadata about the operation.
   */
  metadata?: Record<string, string>;
}

/**
 * Contains the result of a publish operation.
 */
export interface PublishResult {
  /**
   * An array of message serials corresponding 1:1 to the messages that were published.
   * A serial may be null if the message was discarded due to a configured conflation rule.
   */
  serials: (string | null)[];
}

/**
 * Contains the result of an update or delete message operation.
 */
export interface UpdateDeleteResult {
  /**
   * The serial of the new version of the updated or deleted message.
   * Will be null if the message was superseded by a subsequent update before it could be published.
   */
  versionSerial: string | null;
}

/**
 * The namespace containing the different types of message actions.
 */
declare namespace MessageActions {
  /**
   * Message action for a newly created message.
   */
  type MESSAGE_CREATE = 'message.create';
  /**
   * Message action for an updated message. The `serial` field identifies the message of which this is
   * an update. The update will have a newer `version` compared with the original message.create message.
   */
  type MESSAGE_UPDATE = 'message.update';
  /**
   * Message action for a deleted message. The `serial` field identifies the message which is being deleted.
   * The delete will have a newer `version` compared with the original message.create message.
   */
  type MESSAGE_DELETE = 'message.delete';
  /**
   * Message action for a meta-message (a message originating from ably rather than being explicitly
   * published on a channel), containing eg inband channel occupancy events or some other information
   * requested by channel param.
   */
  type META = 'meta';
  /**
   * Message action for a message containing the latest rolled-up summary of annotations
   * that have been made to this message. Like an update, but only updates the summary, so
   * the message.serial is the serial of the message for which this is a summary.
   */
  type MESSAGE_SUMMARY = 'message.summary';
  /**
   * Message action for an appended message. The `serial` field identifies the message to which
   * data is being appended. The `data` field is appended to the previous message's data, while
   * all other fields replace the previous values.
   */
  type MESSAGE_APPEND = 'message.append';
}

/**
 * Describes the possible action types used on an {@link Message}.
 */
export type MessageAction =
  | MessageActions.MESSAGE_CREATE
  | MessageActions.MESSAGE_UPDATE
  | MessageActions.MESSAGE_DELETE
  | MessageActions.META
  | MessageActions.MESSAGE_SUMMARY
  | MessageActions.MESSAGE_APPEND;

/**
 * A message received from Ably.
 */
export type InboundMessage = Omit<Message, 'connectionKey'> &
  Required<Pick<Message, 'id' | 'timestamp' | 'action' | 'version' | 'annotations'>>;

/**
 * Static utilities related to messages.
 */
export interface MessageStatic {
  /**
   * A static factory method to create an `InboundMessage` object from a deserialized InboundMessage-like object encoded using Ably's wire protocol.
   *
   * @param JsonObject - A `InboundMessage`-like deserialized object.
   * @param channelOptions - A {@link ChannelOptions} object. If you have an encrypted channel, use this to allow the library to decrypt the data.
   * @returns A promise which will be fulfilled with an `InboundMessage` object.
   */
  fromEncoded: (JsonObject: any, channelOptions?: ChannelOptions) => Promise<InboundMessage>;
  /**
   * A static factory method to create an array of `InboundMessage` objects from an array of deserialized InboundMessage-like object encoded using Ably's wire protocol.
   *
   * @param JsonArray - An array of `InboundMessage`-like deserialized objects.
   * @param channelOptions - A {@link ChannelOptions} object. If you have an encrypted channel, use this to allow the library to decrypt the data.
   * @returns A promise which will be fulfilled with an array of {@link InboundMessage} objects.
   */
  fromEncodedArray: (JsonArray: any[], channelOptions?: ChannelOptions) => Promise<InboundMessage[]>;
}

/**
 * The `PresenceActions` namespace describes the possible values of the {@link PresenceAction} type.
 */
declare namespace PresenceActions {
  /**
   * A member is not present in the channel.
   */
  type ABSENT = 'absent';
  /**
   * When subscribing to presence events on a channel that already has members present, this event is emitted for every member already present on the channel before the subscribe listener was registered.
   */
  type PRESENT = 'present';
  /**
   * A new member has entered the channel.
   */
  type ENTER = 'enter';
  /**
   * A member who was present has now left the channel. This may be a result of an explicit request to leave or implicitly when detaching from the channel. Alternatively, if a member's connection is abruptly disconnected and they do not resume their connection within a minute, Ably treats this as a leave event as the client is no longer present.
   */
  type LEAVE = 'leave';
  /**
   * An already present member has updated their member data. Being notified of member data updates can be very useful, for example, it can be used to update the status of a user when they are typing a message.
   */
  type UPDATE = 'update';
}
/**
 * Describes the possible actions members in the presence set can emit.
 */
export type PresenceAction =
  | PresenceActions.ABSENT
  | PresenceActions.PRESENT
  | PresenceActions.ENTER
  | PresenceActions.LEAVE
  | PresenceActions.UPDATE;

/**
 * Contains an individual presence update sent to, or received from, Ably.
 */
export declare interface PresenceMessage {
  /**
   * The type of {@link PresenceAction} the `PresenceMessage` is for.
   */
  action: PresenceAction;
  /**
   * The ID of the client that published the `PresenceMessage`.
   */
  clientId: string;
  /**
   * The ID of the connection associated with the client that published the `PresenceMessage`.
   */
  connectionId: string;
  /**
   * The payload of the `PresenceMessage`.
   */
  data: any;
  /**
   * This will typically be empty as all presence messages received from Ably are automatically decoded client-side using this value. However, if the message encoding cannot be processed, this attribute will contain the remaining transformations not applied to the data payload.
   */
  encoding: string;
  /**
   * A JSON object of arbitrary key-value pairs that may contain metadata, and/or ancillary payloads. Valid payloads include `headers`.
   */
  extras: any;
  /**
   * A unique ID assigned to each `PresenceMessage` by Ably.
   */
  id: string;
  /**
   * The time the `PresenceMessage` was received by Ably, as milliseconds since the Unix epoch.
   */
  timestamp: number;
}

/**
 * Static utilities related to presence messages.
 */
export interface PresenceMessageStatic {
  /**
   * Decodes and decrypts a deserialized `PresenceMessage`-like object using the cipher in {@link ChannelOptions}. Any residual transforms that cannot be decoded or decrypted will be in the `encoding` property. Intended for users receiving messages from a source other than a REST or Realtime channel (for example a queue) to avoid having to parse the encoding string.
   *
   * @param JsonObject - The deserialized `PresenceMessage`-like object to decode and decrypt.
   * @param channelOptions - A {@link ChannelOptions} object containing the cipher.
   */
  fromEncoded: (JsonObject: any, channelOptions?: ChannelOptions) => Promise<PresenceMessage>;
  /**
   * Decodes and decrypts an array of deserialized `PresenceMessage`-like object using the cipher in {@link ChannelOptions}. Any residual transforms that cannot be decoded or decrypted will be in the `encoding` property. Intended for users receiving messages from a source other than a REST or Realtime channel (for example a queue) to avoid having to parse the encoding string.
   *
   * @param JsonArray - An array of deserialized `PresenceMessage`-like objects to decode and decrypt.
   * @param channelOptions - A {@link ChannelOptions} object containing the cipher.
   */
  fromEncodedArray: (JsonArray: any[], channelOptions?: ChannelOptions) => Promise<PresenceMessage[]>;

  /**
   * Initialises a `PresenceMessage` from a `PresenceMessage`-like object.
   *
   * @param values - The values to intialise the `PresenceMessage` from.
   */
  fromValues(values: Partial<Pick<PresenceMessage, 'clientId' | 'data' | 'extras'>>): PresenceMessage;
}

/**
 * The namespace containing the different types of annotation actions.
 */
declare namespace AnnotationActions {
  /**
   * Annotation action for a created annotation.
   */
  type ANNOTATION_CREATE = 'annotation.create';
  /**
   * Annotation action for a deleted annotation.
   */
  type ANNOTATION_DELETE = 'annotation.delete';
}

/**
 * The possible values of the 'action' field of an {@link Annotation}.
 */
export type AnnotationAction = AnnotationActions.ANNOTATION_CREATE | AnnotationActions.ANNOTATION_DELETE;

/**
 * Static utilities related to annotations.
 */
export interface AnnotationStatic {
  /**
   * Decodes a deserialized `Annotation`-like object. Any residual transforms that cannot be decoded or decrypted will be in the `encoding` property. Intended for users receiving messages from a source other than a REST or Realtime channel (for example a queue) to avoid having to parse the encoding string.
   *
   * @param JsonObject - The deserialized `Annotation`-like object to decode and decrypt.
   * @param channelOptions - A {@link ChannelOptions} object containing the current channel options.
   */
  fromEncoded: (JsonObject: any, channelOptions?: ChannelOptions) => Promise<Annotation>;
  /**
   * Decodes an array of deserialized `Annotation`-like objects. Any residual transforms that cannot be decoded or decrypted will be in the `encoding` property. Intended for users receiving messages from a source other than a REST or Realtime channel (for example a queue) to avoid having to parse the encoding string.
   *
   * @param JsonArray - An array of deserialized `Annotation`-like objects to decode and decrypt.
   * @param channelOptions - A {@link ChannelOptions} object containing the current channel options.
   */
  fromEncodedArray: (JsonArray: any[], channelOptions?: ChannelOptions) => Promise<Annotation[]>;
}

/** The summary entry for aggregated annotations that use the distinct.v1
 * aggregation method. */
export interface SummaryDistinctValues {
  [key: string]: SummaryClientIdList;
}

/** The summary entry for aggregated annotations that use the unique.v1
 * aggregation method. */
export interface SummaryUniqueValues {
  [key: string]: SummaryClientIdList;
}

/** The summary entry for aggregated annotations that use the multiple.v1
 * aggregation method. */
export interface SummaryMultipleValues {
  [key: string]: SummaryClientIdCounts;
}

/** The summary entry for aggregated annotations that use the flag.v1
 * aggregation method; also the per-name value for some other aggregation methods. */
export interface SummaryClientIdList {
  /** The total number of clients who have published an annotation with this name (or
   * type, depending on context). */
  total: number;
  /** A list of the clientIds of all clients who have published an annotation with this name (or
   * type, depending on context). */
  clientIds: string[];
  /** Whether the list of clientIds has been clipped due to exceeding the maximum number of
   * clients. */
  clipped: boolean;
}

/** The per-name value for the multiple.v1 aggregation method. */
export interface SummaryClientIdCounts {
  /** The sum of the counts from all clients who have published an annotation with this
   * name */
  total: number;
  /** A list of the clientIds of all clients who have published an annotation with this
   * name, and the count each of them have contributed. */
  clientIds: { [key: string]: number };
  /** The sum of the counts from all unidentified clients who have published an annotation with this
   * name, and so who are not included in the clientIds list */
  totalUnidentified: number;
  /** Whether the list of clientIds has been clipped due to exceeding the maximum number of
   * clients. */
  clipped: boolean;
  /** The total number of distinct clientIds in the map (equal to length of map if clipped is false). */
  totalClientIds: number;
}

/** The summary entry for aggregated annotations that use the total.v1
 * aggregation method. */
export interface SummaryTotal {
  /** The total number of clients who have published an annotation with this name (or
   * type, depending on context). */
  total: number;
}

/** The different possible values of the Message.summary map. */
export type SummaryEntry =
  | SummaryDistinctValues
  | SummaryUniqueValues
  | SummaryMultipleValues
  | SummaryClientIdList
  | SummaryTotal;
