"use strict";
var fs   = require('fs');
var path = require('path');
var vm   = require('vm');

var includeScript = function(name) {
	var filename = path.resolve(__dirname, name);
	return vm.runInThisContext(fs.readFileSync(filename, 'utf8'), filename);
};

/* include libraries */
includeScript('./platform.js');
includeScript('./lib/util/defaults.js');
includeScript('./lib/util/bufferutils.js');
includeScript('../common/lib/util/utils.js');
includeScript('./lib/util/http.js');
includeScript('../common/lib/util/defaults.js');
includeScript('../common/lib/util/eventemitter.js');
includeScript('../common/lib/util/logger.js');
includeScript('../common/lib/util/multicaster.js');
includeScript('./lib/util/crypto.js');
includeScript('../common/lib/types/errorinfo.js');
includeScript('../common/lib/types/message.js');
includeScript('../common/lib/types/presencemessage.js');
includeScript('../common/lib/types/protocolmessage.js');
includeScript('../common/lib/types/stats.js');
includeScript('../common/lib/types/devicedetails.js');
includeScript('../common/lib/types/pushchannelsubscription.js');
includeScript('../common/lib/transport/connectionerror.js');
includeScript('../common/lib/transport/messagequeue.js');
includeScript('../common/lib/transport/protocol.js');
includeScript('../common/lib/transport/connectionmanager.js');
includeScript('../common/lib/transport/transport.js');
includeScript('../common/lib/transport/websockettransport.js');
includeScript('../common/lib/transport/comettransport.js');
includeScript('../common/lib/client/resource.js');
includeScript('../common/lib/client/paginatedresource.js');
includeScript('../common/lib/client/auth.js');
includeScript('../common/lib/client/connectionstatechange.js');
includeScript('../common/lib/client/channelstatechange.js');
includeScript('../common/lib/client/connection.js');
includeScript('../common/lib/client/presence.js');
includeScript('../common/lib/client/push.js');
includeScript('../common/lib/client/channel.js');
includeScript('../common/lib/client/realtimechannel.js');
includeScript('../common/lib/client/realtimepresence.js');
includeScript('../common/lib/client/rest.js');
includeScript('../common/lib/client/realtime.js');
includeScript('./lib/transport/nodecomettransport.js');

var Realtime = module.exports = global.Realtime;
Realtime.BufferUtils = global.BufferUtils;
Realtime.Crypto = global.Crypto;
Realtime.Defaults = global.Defaults;
Realtime.Http = global.Http;
Realtime.Utils = global.Utils;
Realtime.Message = global.Message;
Realtime.PresenceMessage = global.PresenceMessage;
Realtime.ProtocolMessage = global.ProtocolMessage;
Realtime.ConnectionManager = global.ConnectionManager;
