name: Features

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      deployments: write
      id-token: write
    uses: ably/features/.github/workflows/sdk-features.yml@6b3fc7a8ede2ebdd7a6325314f3a96c6466f1453 # main
    with:
      repository-name: ably-js
    secrets:
      ABLY_AWS_ACCOUNT_ID_SDK: ${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}
