name: Publish to CDN
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    # These permissions are necessary to run the configure-aws-credentials action
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.event.inputs.version }}
          persist-credentials: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/prod-ably-sdk-cdn
          role-session-name: '${{ github.run_id }}-${{ github.run_number }}'
      - name: Use Node.js 20.x
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: 20.x
      - run: npm ci
      - env:
          VERSION: ${{ github.event.inputs.version }}
        run: node scripts/cdn_deploy.js --skipCheckout --tag="$VERSION"
