name: Test browser
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-browser:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            browser: [webkit]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps
      - env:
          PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
          TEST_OBSERVABILITY_SERVER_AUTH_KEY: ${{ secrets.TEST_OBSERVABILITY_SERVER_AUTH_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ably-cocoa-scripts/continuously-run-tests-and-upload-results.sh --script test:playwright --job-index ${{ strategy.job-index }}
