name: Test browser
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-browser:
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
        matrix:
            browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - name: Install playwright dependencies
        run: sudo npx playwright install-deps
      - env:
          PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
        run: npm run test:playwright
